# Generated by Django 4.1.6 on 2023-02-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_rename_user_meal_user_one_cookbookuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='user_one',
            new_name='user',
        ),
    ]
