# Generated by Django 4.1.6 on 2023-02-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_rename_user_one_meal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingridient',
            name='ico',
        ),
        migrations.AddField(
            model_name='meal',
            name='ico',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
