# Generated by Django 4.1.6 on 2023-02-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_remove_ingridient_ico_meal_ico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ico',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
